
#======================================================================
# File: BUILD
# Date: Spring 2022
# Auth: S. Bowers
# Desc: Bare-bones Bazel BUILD file for HW-1
#======================================================================

load("@rules_java//java:defs.bzl", "java_test")

java_binary(
  name = "mypl",
  srcs = glob(["src/*.java"]),
  main_class = "MyPL",
)




